### PR TITLE
Material tooltips translatable 

### PR DESCRIPTION
**Pull request by FrutyX**
We gucci, Apo?

### CODE REVIEW

**Comment by GreatApo** [comment]
We gucci Fruty!

**Comment by FrutyX** [comment]
Guess I'll just click on it.

**Comment by SleepingShadow-bit** [comment]
Is this a visible innovation?  I'm a noob here for the details xD

**Comment by FrutyX** [comment]
It's this:

trans

I am aware that some languages have it only as Prefix and Suffix, so for example germany has Suffix too, I haven't thought about a workaround yet, you can either just add it there so missing translation script will ignore it or well, you ignore it, for now.

**Comment by SleepingShadow-bit** [comment]
Aaa Okey =) thx

**Pull request merged**
