### PR TITLE
Used the unused description in Gold & XP Stats

### PR DESCRIPTION
**Pull request by FrutyX**
What ya think, Mr. Apo?

gold

### CODE REVIEW

**Comment by GreatApo** [comment]
Are we sure gold is double counted?

**Comment by FrutyX** [comment]
Well, basically yeah.

#248 (hidden comments)
comment

I can probably change the description to:

**Selling items will double your gold earnings (when saving gold via items).**

**Comment by GreatApo** [comment]
Maybe:
Selling items you have bought will double your gold earnings.

**Comment by FrutyX** [comment]
Yea, that's much better, we have a deal. :D

**Pull request merged**
