### PR TITLE
Audio system cleanup (#278)

### PR DESCRIPTION
**Pull request by FrutyX**
Simpler, cleaner.

Testing revealed one non-important error (in #278), other than that, the system seems to be working just fine.

### CODE REVIEW

**Comment by FrutyX** [comment]
mind-blown-mind

**Comment by FrutyX** [comment]
And yeah, I did removed the channels - simplify system, clean unused code.

You have your backups, you can always bring them back if you ever wanted to really finish it.

I honestly think, that we can live without them.

**Comment by GreatApo** [comment]
Thanos, if it is working and it is simpler, lets just go with it. We had enough problems with sounds and there is no reason to be complex.

**Comment by FrutyX** [comment]
I've revived the sound for auction change notifications I originally removed because it was meant for the channels, tested, it works, no errors.

**Comment by FrutyX** [comment]
Gram talking about bombs... while somewhere it is indeed ticking 😃.

Just give up Gram, give up.

I may do some more changes or cleanups to this when (if) it gets into master, IF there will be a need for it, there may be some remnants left I didn't noticed, what matters is that it is working and bug-free/error-free.

I currently have too many different GCA versions, so I am waiting for results for the pull requests, anything can be fixed later.

**Comment by GramThanos** [comment]
:P I don't know what you are talking about. Sound system was working haha.

From my side of view, this is not merged yet only because I want to review the code a bit (both to know what is currently in place and to check for any bugs).

PS: Good job!

**Pull request merged**
