### PR TITLE
Menu - auction quick links

### PR DESCRIPTION
**Pull request by FrutyX**
@GreatApo eyyyyyyyyyyyyyyy, what do ya say?

### CODE REVIEW

**Comment by FrutyX** [comment]
Food not included because it is already in the shortcuts bar.

**Comment by GreatApo** [comment]
The reason I haven't added these links is because we need to drop support for the quick link to the second auction. I believe it is more important to have a quick link to the second auction.

**Comment by FrutyX** [comment]
Ah, you can never make it easy, can you? Alright, I think we can have both, but I will have to play with it more and see what I can do.

**Comment by FrutyX** [comment]
Uh, I don't have any ideas today.

With the latest commit to this, I can at least show you what I was trying to achieve.

First, it's stupid to add the same script again only few things edited and second, there is a problem that the opacity does not stay when the page is refreshed and icons are shown, obviously because it's on a onclick function.

I've been just doing some spaghetti....

**Comment by GreatApo** [comment]
> I've fixed the opacity thing, however it's a code mess I would say, if Thanos sees this, he will lose all his hair, for me, it's a working mess, hehe.
> 
> Now I'll await Apo's response (hopefully not Gram's, muhehe).

I still don't see how you can directly (one click) go to the the second auction... which I think it is more important than going directly to specific categories. Personally I never use these shortcuts for the market either. We do have the function that remembers the last category you visited which probably does most of the job nice and easy

**Comment by FrutyX** [comment]
Does this ring any bell?

auc

**Comment by GreatApo** [comment]
Yes, that is probably the best you can do (sorry I thought it was commented in the code). I will have a better look and try to fix some style problems too.

**Comment by FrutyX** [comment]
It's not perfect, but it does what it's supposed to do and it does not look that bad.

There was no space to try another solution and I did not want it to go outside the menu, that would look horrible. I've been running it all day and it seems fine, no errors logged. As usually, you can review and improve the code for the best results, in it's current state - it's working just fine.

**Comment by FrutyX** [comment]
Whoar, so you did some big changes to it, and made it ten times better, it indeed looks nice now, it needed much more changes in the end. Nice and thanks :).

**Comment by FrutyX** [comment]
@GreatApo by the way, I am not sure if you noticed, but after a page refresh with the menu opened, it's colliding with the ">", but it's a small design thing.

cld

**Comment by GreatApo** [comment]
> @GreatApo by the way, I am not sure if you noticed, but after a page refresh with the menu opened, it's colliding with the ">", but it's a small design thing.
> 
> cld
> 

Oups

**Pull request merged**
