### PR TITLE
Reworked and updated Czech translation (cs.js)

### PR DESCRIPTION
**Pull request by FrutyX**
Hello !

Well,this took a while,the old (and current) file is a mess,so I took your english version and reworked the whole Czech translation file with it,I have added all categories ( //category) and all lines that were missing in this file,everything was fully translated,so the addon should be now 100% translated for Czech language.

I do believe and hope I didn't make some mess in the codes,but I have checked it few times and it should be just OK,nothing should be missing.

Hopefully we can see this translation live soon,so I can at least say that it was worth all that time and work,feel free to lemme know if there are any problems or anything else.

Note: I've added my name there as well,but you are the boss,edit it if needed (Nekros) :)

### CODE REVIEW

**Comment by GramThanos** [comment]
Almost :P
image

Great work!

**Comment by GramThanos** [comment]
I added the missing keys in a comment.
It would be awesome if you can translate them!
😄

**Comment by FrutyX** [comment]
@GramThanos Done ! If  there is anything else,just let me know,glad to help :)

**Comment by GramThanos** [comment]
@FrutyX Good job!

image

**Pull request merged**
