### PR TITLE
Added translation codes

### PR DESCRIPTION
**Pull request by Emefar**

### CODE REVIEW

**Comment by GramThanos** [comment]
Let me ask some changes.

Sync is a category id, so we use lowercase, 
thus `gca_locale.get("Sync", "are_you_sure")` should be `gca_locale.get("sync", "are_you_sure")`

`Yes` and `No` translations are general, so they should go under the general category.

We usually don't use `gca_locale.get("settings", "category_data$cross_browser_login")` outside of the settings, but since it is the same translation its OK.

**Comment by GramThanos** [comment]
Ah... and GOOD MORNING! 😄

**Comment by GramThanos** [comment]
Now the sync is ready! Thanks for the help!
Can you update the `tr.js` (based on 418727df5fd158e6403357d132b599335e32fde9)

**Comment by Emefar** [comment]
> Let me ask some changes.
> 
> Sync is a category id, so we use lowercase,
> thus `gca_locale.get("Sync", "are_you_sure")` should be `gca_locale.get("sync", "are_you_sure")`
> 
> `Yes` and `No` translations are general, so they should go under the general category.
> 
> We usually don't use `gca_locale.get("settings", "category_data$cross_browser_login")` outside of the settings, but since it is the same translation its OK.

Yes you're right. This is my mistake. Thank you for editing :)

**Comment by GramThanos** [comment]
No, no. It's not a mistake. It is just the way I like it best. 😄 

The rest of the code has some inconsistencies like these too, but we try to minimize them.
It's just a way to avoid future code bugs.

**Pull request merged**
