### PR TITLE
Packages icons fix

### PR DESCRIPTION
**Pull request by FrutyX**
For #261

Is it good? It looks good.

### CODE REVIEW

**Comment by GramThanos** [comment]
Is this the expected behaviour?
image

**Comment by Zitronenen** [comment]
It looks good =)

**Comment by FrutyX** [comment]
Yes, it's not under the item hidden, but on it. As expected.

**Comment by FrutyX** [comment]
I got the same idea about the first icon, but I completely forgot about server with different sides.

And that's why I create pull requests, nothing is perfect.

**Comment by GramThanos** [comment]
@GreatApo if you are OK with this, we are accepting it.

**Comment by FrutyX** [comment]
Apo is probably busy preparing for Christmas :P.

apo

**Comment by FrutyX** [comment]
Adding it like "10 000" won't save it, but that's how it is supposed to work, right? Since you added dots. Just making sure it's not some bug.

I don't really know how to further test this, it seems all working and I doubt a script will make a mistake in calculations.
By the way, you have no idea, how much I needed this years ago.

**Comment by Zitronenen** [comment]
Is it possible to search for the suffix / prefix unknown with the special filter?

**Pull request merged**
