### PR TITLE
de translation sleeping

### PR DESCRIPTION
**Pull request by SleepingShadow-bit**

### CODE REVIEW

**Comment by FrutyX** [comment]
@SleepingShadow-bit no harm in translating it, some languages have it translated, it may be used in the future, but it also may be not.

**Comment by FrutyX** [comment]
I don't know what it is actually, it's probably something Thanos was plotting, sounds like it could export a log with errors, or something like that.

**Comment by GreatApo** [comment]
> @GreatApo the en.js file says the following: category_data$export_error_player_settings : "Export unknown-user data to file", // TODO: This may be removed on the future ...So I didn't translate it. What happens to that?

Each player has an id in the game. We save the addon data based on this ID. Sometimes we were not able to identify the player ID and when that happens we used to save data under the ID 0. This was use to extract data from that "0" player. However, I think Thanos has find workarounds on problems identifying the ID, so that is probably not needed any more.

**Comment by GreatApo** [comment]
And thanks for the translation!

**Pull request merged**
