### PR TITLE
Low health warning #84

### PR DESCRIPTION
**Pull request by FrutyX**
@GramThanos @GreatApo I don't know which one of you is available and lurking, this is basically complete, it only doesn't contain `gca_notifications.browser` and I am sure you would rather use that, but I wasn't been able to make it work, for some reason, and I got tired of trying to make it work, so I did it the clean javascript way, you probably want to change it...

### CODE REVIEW

**Comment by GramThanos** [comment]
Regarding the browser notifications, your browser is blocking them. There should be an icon somewhere around the address bar that if you click it, it will ask you to allow notifications.

**Comment by FrutyX** [comment]
> Regarding the browser notifications, your browser is blocking them. There should be an icon somewhere around the address bar that if you click it, it will ask you to allow notifications.

Eh, no? My solution is working, GCA solution wasn't, but that's not GCA's fault, I haven't coded it properly.

It's weird tho, that I put the same `gca_notifications.browser` code in my console, and I got a notification, but it did not worked in the feature... and `gca_notifications.error` did, but like I said, probably just badly coded.

**Comment by FrutyX** [comment]
@GramThanos thank you for the cleanup btw, I try to fix it next time... I don't know why Git has 8 default and Notepad++ 4 default, I haven't changed it.

**Comment by FrutyX** [comment]
...or like I avoid my responsibilities
aware

**Comment by GramThanos** [comment]
:P

**Comment by FrutyX** [comment]
I'll wait for the greater brother... haha.

**Comment by FrutyX** [comment]
If I just do this:
`gca_notifications.browser(false, gca_locale.get("global", "health_notification") + " " + gca_options.get("global", "health_warning") + "%!");`

and put it in my console, it normally pops up, but if I put it in the function, it doesn't work. Once again I am missing a puzzle piece.

**Comment by SleepingShadow-bit** [comment]
Hello, instead of a browser popup, a kind of click block would also be conceivable?  Above a certain HP value, the Expi / dungeon / arena buttons will be greyed out

**Comment by FrutyX** [comment]
That is also possible, but I have to handle the problem above first. Then I will see what can be done.

**Comment by SleepingShadow-bit** [comment]
Understood.  Was a short inspiration =)

**Comment by FrutyX** [comment]
Since there is a shortage for developers, and I have already another project waiting, I did some little improvements to the notification (without using gca func then) and I am now merging this.

**Comment by GreatApo** [comment]
The browser notifications were used to that you can get a notification while you are not on the Gladiatus page, however the heath is mainly updated if you manually refresh the page, were you can see the in page notification anyway... so I don't see how this is helpful... am I missing the goal?

**Comment by FrutyX** [comment]
Actually I don't care, I only know that Thanos usually reworks something if gca had already a tool for this (in this case it's `gca_notifications.browser`), but that did not worked for me, so I just did it the normal javascript, there isn't really a problem with it, it's just not using gca function that was meant to do this, but there is no real loss, I think.

**Comment by GreatApo** [comment]
I thought you would know by know that only my stuff are always working XD

**Comment by FrutyX** [comment]
I've heard the same from a guy that... almost looked like your brother 😄

**Comment by GreatApo** [comment]
Thanos code is like a poem. Sometimes it makes sense, others it doesn't, but most of the time people are trying to find a meaning :P

**Comment by GramThanos** [comment]
You could have stopped at poem.

**Comment by FrutyX** [comment]
Haha.

**Pull request merged**
