### PR TITLE
Added Global Arena Variables

### PR DESCRIPTION
**Pull request by Emefar**

### CODE REVIEW

**Comment by Emefar** [comment]
why is that? I think global arena works fine. What do you intend to add to the global arena?

**Comment by GramThanos** [comment]
We are not sure yet.

Also we try to minimize translations usage because they cause problems. Your's are probably just fine, but since you code I may as well give you some tips (from my experience).

For example, `Attack player XY` is not always expressed as `locale_attack + ' ' + player_name` in every language, so the translation has to be `Attack player {{name}}` sin order to let the translator place the player's name where ever he wants. The same problems can be faced when printing times or numbers, that's why some times we (as programmers) print time as `03:40` and not `3 hours 40 minutes`. In our case, for the addon, the main problem is with the Arabic servers that they are right-to-left, so I personally try to keep the extension compatible with their needs.

That is why we clean the code of a feature after we think it is ready and we apply the locale functions as smarter as we can at the end.

I don't think that you did something wrong, I am just not ready to review this yet since we don't know exactly what changes we will make. But it will be probably be merged.

**Comment by Emefar** [comment]
You are totally right. Attack player {{name}} is better then my translation. I understand now why you waiting translate global arena. You want whole codes are be clean and optimized. If you want delete my pull request.

**Comment by GramThanos** [comment]
No, I think we will merge this. But not right now.

**Comment by GramThanos** [comment]
I updated this from master, and tried to clean up the conflicts.
Some, translations ids were changed and some other were removed (as there will be changes).

**Pull request merged**
