### PR TITLE
GCA cookies upgrade (fix for #260)

### PR DESCRIPTION
**Pull request by FrutyX**
Fix for #260.

You might want to edit or test it, to be sure, this was a little butchery for me, but it does work.

Tested on Firefox, Edge and Chrome.

exper

### CODE REVIEW

**Comment by GramThanos** [comment]
I think that since that cookies re used only by the addon, you can also set `SameSite` to `Strict`. Can you test it?

**Comment by FrutyX** [comment]
Hmm, yes, it seems to be working, need to keep in mind that Strict does not allow cross-site requests, I thought it could affect the Global Arena, but I wasn't checking it's source code and it seems working.

I'll stay with Strict to see if there are any problems, you gotta decide which one we use and I'll edit my pull request (or just add it and edit it by yourself, doesn't matter), if you are sure we will not break something, then why not, I guess.

**Comment by FrutyX** [comment]
it seems it's alright, changed the pull request to Strict.

**Comment by GramThanos** [comment]
> I thought it could affect the Global Arena, but I wasn't checking it's source code and it seems working.

Just an explanation.

Cookies from domain X will never be transmitted to another domain Y.
But if a website from domain Y do a request towards the domain X the browser will add the domain X's emails.
For example, you are logged into you bank account on bank.com and you visit a website malware.com which creates a requests to bank.com/transfer/$100/evil-account which will be a valid request and with your cookies. Usually this is mitigated using anti-CSRF (cross site request forgery) tokens (like the `sh` value you see on the Gladiatus URL). `SameSite` is another measure trying to protect you from such attacks.

**Pull request merged**
