### PR TITLE
change auction tabs to auto width

### PR DESCRIPTION
**Pull request by MiguelSOliveira**
Before:

imagem

After:

imagem

### CODE REVIEW

**Comment by FrutyX** [comment]
Bruh, for me, it looks terrible.

bruh

You gotta keep in mind that everyone has a little different UI because of different languages (pixels are different). And for me, original looks best.

**Comment by MiguelSOliveira** [comment]
I'm sorry, how does it look terrible?

**Comment by FrutyX** [comment]
Because it's this:

bruh2

vs

bruh

Which one would you prefer? Well I prefer the original, so the first one.

You are doing Gameforge's dirty work, they should fix it in the first place, but they won't, because they don't give a shit.

**Comment by MiguelSOliveira** [comment]
And for the English players? Which one do you prefer?

**Comment by FrutyX** [comment]
Then don't use auto, and make it with a fixed size, so mine doesn't look like small crap.

**Comment by FrutyX** [comment]
zindex

Ever heard about z-index?

**Comment by MiguelSOliveira** [comment]
I'm sorry, just to clarify, are you being sarcastic or are you actually wondering if I've heard of z-index?

**Comment by FrutyX** [comment]
Well, yes, I am asking. This seems better, than resizing it, because you never know how it will look like in all languages.

Unless you want to see the whole banner, and you really, really need those few banner pixels to be visible.

**Comment by MiguelSOliveira** [comment]
Honestly I think the 2 lines bother me about as much as you with the small sizes..

I could also add pading to the sides, but I'll wait and see if anyone else has other suggestions or shares the same view as me. 

If not, I'll just add this commit to my fork and use the solution for myself.

**Comment by FrutyX** [comment]
Ever heard about white-space (nowrap)? :D
whitespace

**Comment by MiguelSOliveira** [comment]
How does it look with languages with a bit more text? 🙂

**Comment by FrutyX** [comment]
I think you are just declining any other solution, than yours.

**Comment by MiguelSOliveira** [comment]
That's fair... I'm really not and I'm sorry it comes off that way. 

I'm trying to implement responsive design, that's all.

**Comment by MiguelSOliveira** [comment]
If we are okay with just fixing English, the simplest solution is to increase width by 1 pixel.

That would solve my problem, so I'll wait to hear from others if that's enough. If it is, I would be happy with that!

**Comment by GreatApo** [comment]
Guys, there is no reason for sarcasm and offends. We are here with the same goal.

width: auto; combined with an increase of the right-left padding (eg. padding: 3px 8px;) seems a good solution for double line tabs. That been said, we probably need to enable this style only when the problem exists....

**Comment by GreatApo** [comment]
Are you both happy with my last commit 60e033bf2349385d3b13603254af9a37f09463a9 ?

**Comment by FrutyX** [comment]
Miguel has to test it, in my language, there is no single double-line tab. So for me, nothing changed, which is good I think.

Apo has always the best solutions somehow, as always.

**Comment by FrutyX** [comment]
Nvm, I wanted to create an english acc anyway, yep, it seems to be working:

ok

**Comment by MiguelSOliveira** [comment]
Will test tomorrow guys, and will let you know. 

Thank you both for testing!

**Comment by MiguelSOliveira** [comment]
Looks good, I'll close this issue.

Thank you!

**Comment by GramThanos** [comment]
Bug
image

**Pull request closed without merging**
