### PR TITLE
Update tr.js

### PR DESCRIPTION
**Pull request by mattemre**

### CODE REVIEW

**Comment by FrutyX** [comment]
`markets : {
	add_fees_in_price : "Add fees in price"
}`

is missing :).

**Comment by GreatApo** [comment]
Thanks for the translation!

**Comment by mattemre** [comment]
I'm trying to learn javascript by watching videos. how long do you think it will take

**Comment by GreatApo** [comment]
> I'm trying to learn javascript by watching videos. how long do you think it will take

It is different for each person. Also javascript is a weird language relying on HTML and CSS. My tip is: Don't learn to code, code to learn!

**Pull request merged**
