### PR TITLE
add item names in auction house

### PR DESCRIPTION
**Pull request by MiguelSOliveira**
This is guarded under a setting so it should not affect existing configs (default is false) and is optional:

imagem

imagem

### CODE REVIEW

**Comment by FrutyX** [comment]
Obviously I don't want to make it a light neon show, but maybe color the item names? Either with their item quality or just so it is more clearer? Maybe?

**Comment by MiguelSOliveira** [comment]
imagem

Not sure by quality is the best solution here.

**Comment by FrutyX** [comment]
Alright, that's terrible, now when I see it :D quality is a no-go.

**Comment by GreatApo** [comment]
The item shadow hints the quality already, so I wouldn't say it is required. An other way is to add a bullet or an other special character next to the name and color that only.

But it seems fine as it is!

**Comment by MiguelSOliveira** [comment]
yeah I would say this is enough, in my opinion... it serves it's main purpose which is the name being visible.

**Comment by FrutyX** [comment]
Yeah, let's keep it clean then.

**Comment by GreatApo** [comment]
@MiguelSOliveira I see you picked up the code already (options, translations etc)... Nice!

**Comment by MiguelSOliveira** [comment]
cheers bro 👍

**Pull request merged**
