### PR TITLE
Market - custom sell prices (buttons) [#166]

### PR DESCRIPTION
**Pull request by FrutyX**
It ain't perfect, but it is working and surprisingly it doesn't look that bad as I expected.
You most likely want to inspect, test and polish, since my codes are dirty because I am a dirty boi.

Similar to feature request #166.

(Actually I am glad I made it work lol)

### CODE REVIEW

**Comment by GramThanos** [comment]
@FrutyX lets test it a bit.
image

**Comment by FrutyX** [comment]
lol, I love how I do something, and then you go and just rework it, but don't get me wrong, I am glad for it.

It's looks hella awesome, will do some testing.

**Comment by FrutyX** [comment]
Sure Gram, why not 🤣  

haha

**Comment by FrutyX** [comment]
One small thing, it's stupid, but people are writing numbers in various ways, if you add it like "100 000 or 100.000" it will only work as "100". 

But basically it's just a detail.

**Comment by GramThanos** [comment]
I agree, but the problem is that I scripted it to allow floats when you are defining a multiplication.
So x1.5 means 150% of the item price.
Maybe I should change it to percentages instead of floating numbers?

**Comment by FrutyX** [comment]
Damn, now that is a question, I don't know what is better, but percentages does not sound bad too.

I think we need a third person to decide, someone call Apo :D.

**Comment by FrutyX** [comment]
Hmm, don't know your opinion but I was thinking about it a bit, and I believe percentages might be better in the end.

**Comment by FrutyX** [comment]
Adding it like "10 000" won't save it, but that's how it is supposed to work, right? Since you added dots. Just making sure it's not some bug.

I don't really know how to further test this, it seems all working and I doubt a script will make a mistake in calculations.
By the way, you have no idea, how much I needed this years ago.

**Pull request merged**
