### PR TITLE
Hide language flags #377

### PR DESCRIPTION
**Pull request by FrutyX**
Thanos can roast me all he wants, I've tried doing this as much gently as possible. Also originally, I was trying to achieve this purely with javascript, on the way I only found problems, and when it finally worked, it was sometimes bugging out on page load, CSS is just reliable.

Of course you can rework it, but it's fine as it is, no problems found so far.

(I also found, that someone, probably Apo, already prepared the function in global.js, so I have used it)

#377

### CODE REVIEW

**Comment by FrutyX** [comment]
Since it's CSS, I was just thinking, that it would be probably better use preload, rather than init, like I said, I just what was already there. But I also have tried it with preload, and saw basically no difference.

**Comment by FrutyX** [comment]
Oki Thanos, thanks for the advice, I'll change it to preload later. :)

**Comment by SleepingShadow-bit** [comment]
how i can test your code? i want see the results :)

**Comment by FrutyX** [comment]
Any feedback? Working good for you?

So I can merge it, time waits for no one, and so do I.

**Comment by SleepingShadow-bit** [comment]
Just installed it. I like the new ranking! Do you see the flags somewhere else now or just hide them?

**Comment by FrutyX** [comment]
Currently, they should be hidden everywhere except the settings (multi-accounts), for multiple reasons, I will keep them visible there, no harm there.

**Comment by FrutyX** [comment]
I have upgraded the code to prevent errors that could occur when the page has a url submod and the flags are not actually on the page.

**Comment by FrutyX** [comment]
For now, I will merge it.

But it appears, that specifically Firefox is having issues with `document.getElementById("content")` and sometimes it throws a null error, this is also affecting the Gladiatus-Fixes, I've tried removing preload, but it did not do anything... I will have a look at it when I can.

**Pull request merged**
